# Generated by Django 6.0.7 on 2026-07-13 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('price_per_night', models.IntegerField()),
                ('capacity', models.PositiveIntegerField()),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='villas.villa')),
            ],
            options={
                'unique_together': {('villa', 'date')},
            },
        ),
    ]
